/**
 * healRunner.test.ts — Follow-up #3: gated wiring of the HEAL self-healing
 * phase into the live loop (`runTick`), OPT-IN and OFF by default.
 *
 * The HEAL phase internals (gather → resolve → act on a stale+expired claim,
 * the RAIL that a healthy owner is never touched, propose vs act) are covered
 * exhaustively by heal.test.ts + supervisor.test.ts. THESE tests assert only the
 * GATE that this follow-up adds around `runHealPhase` inside `runTick`:
 *
 *   - disabled (the default) ⇒ the HEAL phase is SKIPPED: no gather → resolve →
 *                              report → act runs, so no HEAL finding_report is
 *                              emitted — identical to a loop that never opted in;
 *   - enabled                ⇒ the HEAL phase RUNS: gather → resolve → report
 *                              fires and a HEAL finding_report lands in shared/.
 *
 * The signal we drive the gate with is an open reconcile DRIFT
 * (`reconcile-report.json`), because:
 *   1. `gatherRecoverySignals` turns each drift into a `surface_finding` action,
 *      and the HEAL phase emits a `finding_report` per action — a clean,
 *      deterministic "the phase ran" / "the phase did not run" probe; and
 *   2. unlike a hand-seeded `board.json`, `reconcile-report.json` is NOT
 *      regenerated by the board write that precedes HEAL in the tick, so the
 *      signal reliably survives to the HEAL block.
 * A drift resolves to a report-only `surface_finding` (never an auto-fix), so
 * these tests also confirm the gated path stays within the rails.
 *
 * mocha-tdd + a tmp-dir workspace, same pattern as orchestratorLoop.test.ts.
 */

import * as assert from 'assert';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { runTick, type LoopState } from '../orchestratorLoop';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeTmp(prefix: string): string {
  const d = fs.mkdtempSync(path.join(os.tmpdir(), `autoclaw-healrunner-${prefix}-`));
  fs.mkdirSync(path.join(d, '.autoclaw', 'orchestrator', 'comms', 'heartbeats'), { recursive: true });
  fs.mkdirSync(path.join(d, '.autoclaw', 'orchestrator', 'comms', 'inboxes', 'shared'), { recursive: true });
  fs.mkdirSync(path.join(d, '.autoclaw', 'orchestrator', 'comms', 'claims'), { recursive: true });
  fs.mkdirSync(path.join(d, '.autoclaw', 'orchestrator', 'sprints'), { recursive: true });
  return d;
}

const orch = (r: string) => path.join(r, '.autoclaw', 'orchestrator');
const sharedInbox = (r: string) => path.join(orch(r), 'comms', 'inboxes', 'shared');

const writeJson = (p: string, o: unknown) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(o, null, 2), 'utf8');
};

function freshState(): LoopState {
  return {
    tick: 0, startedAt: new Date().toISOString(), lastTickAt: null,
    totalAgentsSeen: 0, totalTicks: 0, totalErrors: 0, totalDispatches: 0,
    vendorStats: {},
  };
}

/** Count HEAL finding_reports (emitted `from: 'supervisor'`) in the shared inbox. */
function healFindings(root: string): unknown[] {
  let files: string[];
  try { files = fs.readdirSync(sharedInbox(root)); } catch { return []; }
  return files
    .filter(f => f.includes('finding_report'))
    .map(f => { try { return JSON.parse(fs.readFileSync(path.join(sharedInbox(root), f), 'utf8')); } catch { return null; } })
    .filter((m: any) => m && m.from === 'supervisor' && m.type === 'finding_report');
}

/** Seed one open reconcile drift — the HEAL phase turns it into a surface_finding. */
function seedDrift(root: string, taskId = 'C1'): void {
  writeJson(path.join(orch(root), 'reconcile-report.json'), {
    generated_at: new Date().toISOString(),
    sweep_duration_ms: 0,
    drifts: [{ type: 'task_status_mismatch', task_id: taskId, description: 'state/yaml disagree' }],
  });
}

// ---------------------------------------------------------------------------
// Gate: OFF by default
// ---------------------------------------------------------------------------

suite('HEAL gate in runTick — OFF by default (Follow-up #3)', () => {

  test('default (no opts) ⇒ HEAL phase skipped, no HEAL finding emitted', async () => {
    const root = makeTmp('default-off');
    seedDrift(root);

    // No third arg at all — proves the existing 2-arg call site is unchanged
    // AND that the gate defaults to off.
    const result = await runTick(root, freshState());

    assert.strictEqual(result.errors, 0, 'tick should not error');
    assert.strictEqual(healFindings(root).length, 0, 'no HEAL finding_report when off');
  });

  test('explicit selfHealingEnabled:false ⇒ HEAL phase skipped, no HEAL finding', async () => {
    const root = makeTmp('explicit-off');
    seedDrift(root);

    const result = await runTick(root, freshState(), { selfHealingEnabled: false });

    assert.strictEqual(result.errors, 0);
    assert.strictEqual(healFindings(root).length, 0, 'no HEAL finding_report when explicitly off');
  });
});

// ---------------------------------------------------------------------------
// Gate: ON (opt-in)
// ---------------------------------------------------------------------------

suite('HEAL gate in runTick — ON when opted in (Follow-up #3)', () => {

  test('selfHealingEnabled:true ⇒ HEAL phase runs: gather→resolve→report emits a finding', async () => {
    const root = makeTmp('on');
    seedDrift(root);

    const result = await runTick(root, freshState(), { selfHealingEnabled: true });

    assert.strictEqual(result.errors, 0);
    const findings = healFindings(root) as any[];
    assert.ok(findings.length >= 1, 'a HEAL finding_report should be emitted when enabled');
    // Drift is report-only — the rail: it surfaces, never auto-fixes.
    assert.ok(
      findings.some(m => m.payload && m.payload.recovery_kind === 'surface_finding'),
      'drift should resolve to a report-only surface_finding (never an auto-fix)',
    );
  });

  test('enabled but no failure signals ⇒ HEAL runs but takes no action / emits no finding', async () => {
    const root = makeTmp('on-clean');
    // No reconcile-report.json, no stale claims → zero signals.
    const result = await runTick(root, freshState(), { selfHealingEnabled: true });
    assert.strictEqual(result.errors, 0);
    assert.strictEqual(healFindings(root).length, 0, 'no signals ⇒ no HEAL finding even when enabled');
  });
});

// ---------------------------------------------------------------------------
// Symmetry: the ONLY difference between the two paths is the gate.
// ---------------------------------------------------------------------------

suite('HEAL gate in runTick — gate is the only difference (Follow-up #3)', () => {

  test('identical workspace: off ⇒ 0 HEAL findings, on ⇒ >=1 HEAL finding', async () => {
    const offRoot = makeTmp('sym-off');
    const onRoot = makeTmp('sym-on');
    seedDrift(offRoot);
    seedDrift(onRoot);

    await runTick(offRoot, freshState(), { selfHealingEnabled: false });
    await runTick(onRoot, freshState(), { selfHealingEnabled: true });

    assert.strictEqual(healFindings(offRoot).length, 0, 'off path must emit zero HEAL findings');
    assert.ok(healFindings(onRoot).length >= 1, 'on path must emit at least one HEAL finding');
  });
});
