/**
 * agentStyle.ts — pure generator for the `agent-style.md` guide produced by the
 * `/learn` orchestrator (R5.7).
 *
 * `generateAgentStyle` turns aggregated learning signal (successful patterns,
 * patterns to avoid, preferred tools) into a stable, human-readable markdown
 * body. It performs NO I/O, imports no `vscode`, and is fully deterministic so
 * the learn pipeline can diff/regenerate it on every run.
 */

/** Aggregated style signal distilled from analyzed sessions. */
export interface StyleAggregates {
  /** Patterns that led to kept/shipped code — things to keep doing. */
  successfulPatterns: string[];
  /** Patterns that led to discarded work — things to avoid. */
  avoidedPatterns: string[];
  /** Tools/sources that produced the most kept work, most-preferred first. */
  preferredTools: string[];
}

const EMPTY_SECTION = '_None recorded yet._';

function renderList(items: string[]): string {
  const cleaned = items.map((i) => i.trim()).filter((i) => i.length > 0);
  if (cleaned.length === 0) {
    return EMPTY_SECTION;
  }
  return cleaned.map((i) => `- ${i}`).join('\n');
}

/**
 * Build the `agent-style.md` markdown body from aggregated learning signal.
 *
 * @param focus      optional focus area the run was scoped to (free text).
 * @param aggregates successful/avoided patterns + preferred tools. Missing
 *                   fields render as an empty-section placeholder.
 * @returns a deterministic markdown string (no trailing newline).
 */
export function generateAgentStyle(
  focus?: string,
  aggregates?: Partial<StyleAggregates>,
): string {
  const successful = aggregates?.successfulPatterns ?? [];
  const avoided = aggregates?.avoidedPatterns ?? [];
  const tools = aggregates?.preferredTools ?? [];

  const lines: string[] = [];
  lines.push('# Agent Style Guide');
  lines.push('');
  lines.push(
    '_Generated by AutoClaw `/learn`. This file is regenerated on every run from ' +
      'your recent sessions — edit the source signals, not this file._',
  );

  const trimmedFocus = focus?.trim();
  if (trimmedFocus) {
    lines.push('');
    lines.push(`**Focus:** ${trimmedFocus}`);
  }

  lines.push('');
  lines.push('## Successful Patterns');
  lines.push('');
  lines.push(renderList(successful));

  lines.push('');
  lines.push('## Patterns to Avoid');
  lines.push('');
  lines.push(renderList(avoided));

  lines.push('');
  lines.push('## Preferred Tools');
  lines.push('');
  lines.push(renderList(tools));

  return lines.join('\n');
}
