/**
 * orientation.ts — write AutoClaw's authoritative self-description into the
 * workspace as plain files, so ANY agent in ANY tool finds the truth by reading
 * the `.autoclaw/` tree — even when the AutoClaw extension is not installed in
 * that workspace (the common case for non-VS Code hosts like Kiro).
 *
 * Three placements, all rendered from the host-free {@link contract}:
 *   - `.autoclaw/AGENT-ORIENTATION.md` — the full command + store contract.
 *   - `.autoclaw/README.md`           — a one-screen pointer at the top of the tree.
 *   - `.autoclaw/<store>/README.md`   — per-store stubs that sit at the exact
 *     point of confusion (an agent that opens `.autoclaw/kg/` reads, right there,
 *     that it holds coordination facts and that `/index-code` does NOT write it).
 *
 * Content is DETERMINISTIC (no timestamp in the committed body) and written only
 * when it differs from what is on disk, so re-provisioning never churns the tree
 * or git. No `vscode` import — callable from the extension and from skills/tests.
 */

import * as fs from 'fs';
import * as path from 'path';

import { LogFn } from './config';
import { ensureDir, intelligencePaths, toForwardSlash } from './paths';
import {
  CONTRACT_VERSION,
  renderOrientationMarkdown,
  renderStoreReadme,
} from './contract';

/** What {@link writeAgentOrientation} did. */
export interface OrientationWriteResult {
  /** Files (re)written because they were missing or out of date. */
  written: string[];
  /** Files already current. */
  unchanged: string[];
  /** Per-file failures (path + message); never thrown so one bad file can't block the rest. */
  failed: Array<{ path: string; error: string }>;
}

/** Options for {@link writeAgentOrientation}. */
export interface OrientationWriteOptions {
  /** Project name used in the orientation title. Defaults to the workspace folder name. */
  projectName?: string;
  /** Optional warning sink (logger-injection convention). */
  log?: LogFn;
}

/** Write `body` to `file` only when it differs from disk. Returns 'written' | 'unchanged'. */
async function writeIfDiffers(file: string, body: string): Promise<'written' | 'unchanged'> {
  try {
    const existing = await fs.promises.readFile(file, 'utf8');
    if (existing === body) {
      return 'unchanged';
    }
  } catch {
    // missing/unreadable — fall through to write
  }
  await ensureDir(path.dirname(file));
  await fs.promises.writeFile(file, body, 'utf8');
  return 'written';
}

const README_BODY = (autoclawRoot: string): string =>
  [
    '# `.autoclaw/` — AutoClaw coordination, memory & learning',
    '',
    `> Auto-generated by AutoClaw (contract v${CONTRACT_VERSION}).`,
    '',
    'If you are an AI agent working in this repo, **read `AGENT-ORIENTATION.md` (next to this file) first.**',
    'It is the authoritative description of what AutoClaw is, the exact commands, and what each store contains.',
    '',
    'Quick map:',
    '',
    '- `agent-style.md` — learned patterns to follow / avoid (read this first).',
    '- `AGENT-ORIENTATION.md` — full command + on-disk contract.',
    '- `orchestrator/board.json` — current tasks & assignments.',
    '- `orchestrator/comms/inboxes/` — your mailbox + the shared broadcast inbox.',
    '- `vector/` — semantic code/learning index (see `vector/README.md`).',
    '- `kg/` — multi-agent coordination knowledge graph (see `kg/README.md`).',
    '',
    'Do not hand-author your own AutoClaw steering files — these regenerate and a manual copy drifts.',
    '',
  ].join('\n');

/**
 * Write the orientation file set under `<workspaceRoot>/.autoclaw`. Idempotent and
 * churn-free (writes only on difference). Degrade-safe: per-file failures are
 * collected, never thrown.
 */
export async function writeAgentOrientation(
  workspaceRoot: string,
  opts: OrientationWriteOptions = {},
): Promise<OrientationWriteResult> {
  const log = opts.log ?? (() => undefined);
  const paths = intelligencePaths(workspaceRoot);
  const projectName = opts.projectName ?? (path.basename(path.resolve(workspaceRoot)) || 'this repo');

  const orientationBody = renderOrientationMarkdown({ projectName });
  const kgReadme = renderStoreReadme('.autoclaw/kg/kg.db');
  const vectorReadme = renderStoreReadme('.autoclaw/vector/db.sqlite');

  const jobs: Array<{ path: string; body: string }> = [
    { path: toForwardSlash(path.join(paths.root, 'AGENT-ORIENTATION.md')), body: orientationBody },
    { path: toForwardSlash(path.join(paths.root, 'README.md')), body: README_BODY(paths.root) },
  ];
  if (kgReadme) {
    jobs.push({ path: toForwardSlash(path.join(paths.kgDir, 'README.md')), body: kgReadme });
  }
  if (vectorReadme) {
    jobs.push({ path: toForwardSlash(path.join(paths.vectorDir, 'README.md')), body: vectorReadme });
  }

  const written: string[] = [];
  const unchanged: string[] = [];
  const failed: Array<{ path: string; error: string }> = [];

  for (const job of jobs) {
    try {
      const result = await writeIfDiffers(job.path, job.body);
      (result === 'written' ? written : unchanged).push(job.path);
    } catch (err) {
      const error = (err as Error).message;
      failed.push({ path: job.path, error });
      log(`orientation: failed to write ${job.path} — ${error}`);
    }
  }

  return { written, unchanged, failed };
}
